### ISSUE TITLE
Configurable content parameters would be great

### ISSUE THREAD

**Issue by andypillip** [jlarriba/jrmapi#22]
Hi and thanks so much for your work!

I’m using RemarkablePocket to sync Pocket with my Remarkable. It makes use of this library.

Right now, I need to go and correct the font size setting for each article, since the default is way too big for my reading habits. So I thought maybe there’s a config file to configure the standard parameters for uploaded ePubs, where I could adjust the font size.

I poked around in code, and found some hardcoded defaults in `createZipContent`. So I guess currently this is not possible.

What do you think of adding such feature? Is it a lot of work?

Thanks a bunch!

**Comment by jlarriba** [comment]
Hi Andy,

thank you for youtr feedback. It has been long time since I last worked on this library so I do not foresee adding new features to it :(.

However, if your concern is because you are using RemarkablePocket, the developer removed the usage of jrmapi on 31 of August and moved on to use the much better supported rmapi. 

In this regard, any changes I would implement here will not have effect on the latest version of RemarkablePocket.

**Comment by andypillip** [comment]
Oh yeah I missed that detail. Thanks so much for clarifying this quickly.
